[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@ffmpeg-installer/ffmpeg", "fluent-ffmpeg"]
  included_files = ["node_modules/@ffmpeg-installer/ffmpeg/ffmpeg"]

[functions.transcribe]
  # Increase timeout for processing
  timeout = 30
  # Increase memory allocation
  memory = 1024
  # Configure proper headers
  [functions.transcribe.environment]
    CONTENT_TYPE = "application/json"
    CACHE_CONTROL = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = ":content_type"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Disable Next.js plugin
[build.processing]
  skip_processing = true